### ISSUE TITLE
Proguard rules needed for databinding

### ISSUE THREAD

**Issue by wezley98** [QuickPermissions/QuickPermissions#1]
Hi,

I had to add the following proguard rules to compile with your lib, maybe you should consider adding them in a consumer proguard file?

```
-dontwarn android.databinding.**
-keep class android.databinding.** { *; } 
```

**Comment by kirtan403** [comment]
I am confused what this library has to do with data-binding. It doesn't use it at all. Any logs of error you got may help me find what's wrong?

**Comment by kirtan403** [comment]
@wezley98  I have added proguard rules in release 0.3.2. Can you please check and tell me if it works?
