### ISSUE TITLE
Build time greatly increased?

### ISSUE THREAD

**Issue by Ornolfr** [QuickPermissions/QuickPermissions#3]
Has anyone experienced this problem after installing this library?

**Comment by kirtan403** [comment]
For the first time, yes. But sub-sequence builds should be fast.

**Comment by Ornolfr** [comment]
@kirtan403 are you using Instant Run? I don't, and it builds much longer any time I change any code in the class where these annotations are present. Maybe it has something to do with annotation processor? Like, maybe it's because we're not using annotationProcessor/kapt for this lib but classpath for project gradle file and applying the plugin?

**Comment by kirtan403** [comment]
Yes, if you are changing the file annotation is present, it will take some time. But I don't think it should re compile all the files. It will just recompile the file which is changed. So It should not take too much time as you are saying. I have tested it and after initial compilation, it worked pretty fast, even If I modified the file which contains the annotation.

**Comment by MrBIMC** [comment]
I have the same issue, Kotlin project, instant run disabled, compilation times decreased drammatically.  At least by minute. That's super annoying :(

**Comment by kirtan403** [comment]
@MrBIMC I think you mean compilation time increased. Yes, that takes some time to process your files. I have tried a few optimizations but failed to make it work. I can understand the pain as Me too have gone through it. But I am trying and If I get it work, I'll surely post it.

**Comment by Corical** [comment]
Same here, add 40 seconds to build time this side, considering going back to what I had, can't waste time like this. Also don't do instant run, I have my reasons. Actually quite ironic, if you look at the name. Also it is probably worth mentioning on the info page, although you might save time to initially do the permission implementation, you will pay indefinitely (in time) per build.

**Comment by kirtan403** [comment]
@Ornolfr @MrBIMC @Corical I have a good news to all of you. If you are using kotlin, you can use the new [QuickPermissions-Kotlin](https://github.com/QuickPermissions/QuickPermissions-Kotlin) that works out of the box without any gradle plugins and works with instant run.

**Comment by MrBIMC** [comment]
Amazing, thank you!
