### ISSUE TITLE
How to Refer the string constant(created from strings.xml) for rationaleMessage?

### ISSUE THREAD

**Issue by ankithabandaru** [QuickPermissions/QuickPermissions#6]
final String perStr = getString(R.string.app_level_permission_denied_msg);

    @WithPermissions( permissions = {Manifest.permission.CAMERA},
            rationaleMessage = perStr, // seeing error here "Attribute must be constant"
            permanentlyDeniedMessage = perStr)
    public void requestCameraPermission() {
    }

In the above code, when i try to give string constant(created from strings.xml), it is giving error "Attribute must be constant".
Can't we refer this way? How to get the value from Strings.xml ?

**Comment by kirtan403** [comment]
You can't do it right now. I'm planning to add it. But the thing is, annotations doesn't allow dynamic values. Annotations values must be constant. But, for now, this is not possible. I'm sorry for that.

**Comment by kirtan403** [comment]
@ankithabandaru I have a good news for you. If you are using kotlin, you can use the new [QuickPermissions-Kotlin](https://github.com/QuickPermissions/QuickPermissions-Kotlin) that works out of the box without annotations. So you can now use the strings from strings.xml. Head over there to learn how to that. It's simple.

**Comment by ewoks** [comment]
this is still not possible in java version of the library, no? @kirtan403 
Does it need to be const or just final would be enough? I wonder how to go around it when we need localised string? 
Can we use QuickPermissions-Kotlin in just Java App?

**Comment by kirtan403** [comment]
@ewoks I'm sorry, that is not possible in the Java version. As compile time annotation doesn't allow runtime values. My best guess is final won't be allowed as that values can be generated at runtime as final. However, constants are compile time and guaranteed to be the same value all the time. 

For your second question, I think use can use the kotlin version in the java, but for that you might have to use some different callback. In kotlin version, it uses the lambda to pass the callback, however you should be able to use that from java as well. However, I haven't tried that, so I can't guarantee that it will work as expected. I encourage you to try and let me know, I am positive that it should work (with a little different syntax) I guess. All the best 👍

**Comment by ewoks** [comment]
Ok, thanks for clarifications. What would be your best recommendation to use localised messages in dialogs in just Java project? I will check Kotlin lib in the meantime

**Comment by kirtan403** [comment]
As far as I know, using localized messages with Java version is not possible. Please refer to this for the clarification: https://stackoverflow.com/a/10636320/1820644
