### ISSUE TITLE
Is it possible to downgrade requirements?

### ISSUE THREAD

**Issue by isabsent** [QuickPermissions/QuickPermissions#9]
Is it possible to run your  library on **Android Studio 2.3.3**? My `gradle` settings are:
In project level `build.gradle`

    classpath 'com.android.tools.build:gradle:2.3.3'
In app level `build.gradle`

    compileSdkVersion 25
    buildToolsVersion "25.0.3"
and in `gradle-wrapper.properties`

    distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

I can't compile project with above settings:

![quick_permissions](https://user-images.githubusercontent.com/4918293/41707397-37f0f9ca-7568-11e8-848a-55da4dfa98d4.png)

and I can't upgrade gradle plugin to **4.1** staying in **Android Studio 2.3.3**

**Comment by kirtan403** [comment]
@isabsent Can I know why can't you update to 4.1?

**Comment by isabsent** [comment]
I can upgrade to 4.1 but  would not like to do it right now, because I would loose some opportunities I have in 3.3 and have not in 4.1.

**Comment by kirtan403** [comment]
@isabsent I'm afraid you can do that right now.

But, I have a good news for you. If you are using kotlin, you can use the new [QuickPermissions-Kotlin](https://github.com/QuickPermissions/QuickPermissions-Kotlin) that works out of the box without any gradle plugins and works with instant run.
